# Generated by Django 3.0.5 on 2020-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200720_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='work_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
